### ISSUE TITLE
Enable squashing and use PR title/body as commit message

### ISSUE THREAD

**Issue by kayman-mk** [cloudandthings/terraform-aws-costnotifier#26]
Just received the following error message from the workflow:
```
Pull request has only one commit and it's not semantic; this may lead to a non-semantic commit in the base branch (see https://github.community/t/how-to-change-the-default-squash-merge-commit-message/1155). Amend the commit message to match the pull request title, or add another commit.
```

What do you think about activating the squash mode and use the PR title/body as commit message? This can be configured in the settings of the project.

This way there is no error message shown if you have one commit in a branch only.

**Comment by baolsen** [comment]
Hey @kayman-mk thanks for the suggestion.

Squash mode is an option we can use for some PRs, no problem. 

I think the workflow action won't know about these settings and would still fail if a commit is non-semantic.

I think what is needed is a pre-commit check for semantic commit messages. This would also run in the workflow so would be a way to make sure commits are semantic (not just PR title). When a PR is created it uses the commit message for the title, so that would be a solution.

Amending the last commit message is quite easy with `git commit --amend` but when there are many commits it is harder. So pre-commit can help with each commit.

There is a scenario where we could have 2+ semantic commits in the same PR, and don't want to squash because we want to see all changes in the changelog. PR title might only have the message from 1 commit.

What do you think?

_(Aside: I am trying to get this module to a point where we can use it to create a template for our org, as our current template is out of date. Automated changelog is a feature I want to add, which can come from semantic commits. I want to ask Hashicorp if we can add the changelog to the Terraform cloud UI, see changes by version, etc...)_

**Comment by kayman-mk** [comment]
If squashing can't be used --> that's fine. The `amannn/action-semantic-pull-request` workflow action recognizes that squashing is enabled and does not throw the shown error.

EDIT: feel free to close this issue.

**Comment by baolsen** [comment]
Thanks @kayman-mk 

I tried to find & test some tools that can manage semantic commits better, but didn't immediately find anything.

It seems the best approach is as you suggested; use squash-merge with the gitlab setting. And the person doing the merge is responsible for defining the final commit message.

It's a pity there isn't a better (automated) way to manage it but for now, it will work.
